version: "3.3"

services:
  # Backend
  nginxserve:
    image: nginx
    hostname: nginx
    ports:
      - 80:80
      - 8008:8008 # debugging port
    volumes:
      - /rdata/configs/nginx/proxy_static_dynamic.conf.template:/etc/nginx/templates/default.conf.template
      - /rdata/www:/var/www
    links:
      - phpfpm
    environment:
      - PROXY_USE_TLD=local
      - PROXY_USE_IP=syzygy.local
    restart: always
  phpfpm:
    image: php:fpm
    hostname: phpfpm
    volumes:
      - /rdata/www:/var/www
    restart: always
  docker-mdns:
    image: hardillb/nginx-proxy-avahi-helper
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
#      - /rdata/configs/mdns/Procfile:/usr/src/app/Procfile
#      - /rdata/configs/mdns/static_cnames:/static_cnames
    restart: always
  static-mdns:
    build:
      context: .
      dockerfile: static-mdns.Dockerfile
    volumes:
      - /rdata/configs/mdns/static_cnames:/cnames
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    restart: always
  # Applications
#  audioserve:
#    image: izderadicka/audioserve:latest
#    hostname: audioserve
#    command: "--no-authentication /music /audiobooks"
#    ports:
#      - 3000:3000
#    volumes:
#      - /rdata/configs/audioserve:/home/audioserve/.audioserve
#      - /rdata/music:/music
#      - /rdata/audiobooks:/audiobooks
#    restart: always
  filebrowser:
    image: filebrowser/filebrowser:v2
    hostname: filebrowser
    ports:
      - 8080:80
    volumes:
      - /rdata/docstore:/srv
      - /rdata/configs/filebrowser/filebrowser.db:/database.db
      - /rdata/music:/srv/Music (mapped)
      - /rdata/audiobooks:/srv/Audiobooks (mapped)
      - /rdata/onlydocs:/srv/onlydocs (mapped)
    environment:
      - VIRTUAL_HOST=filebrowser.local
    restart: always
  homer:
    image: b4bz/homer:latest
    hostname: homer
    ports:
      - 8086:8080
    volumes:
      - /rdata/configs/homer:/www/assets
    environment:
      - VIRTUAL_HOST=homer.local
    restart: always
piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
		- VIRTUAL_HOST=piwigo.local
    volumes:
      - /rdata/configs/piwigo:/config
      - /rdata/piwigo:/gallery
    ports:
      - 8094:80
    restart: unless-stopped
#  scrutiny:
#    image: ghcr.io/analogj/scrutiny:master-omnibus
#    hostname: scrutiny
#    ports:
#      - 8087:8080
#    volumes:
#      - /run/udev:/run/udev:ro
#      - /rdata/configs/scrutiny:/scrutiny/config
#    devices:
#      - /dev/sda
##      - /dev/sdb
#    cap_add:
#      - SYS_RAWIO
#    environment:
#      - VIRTUAL_HOST=scrutiny.syzygy.local
#    restart: always
#  dokuwiki:
#    # version: Hogfather (number 2020-07-29), patches rolled into it despite the old year
#    image: ghcr.io/linuxserver/dokuwiki:version-2020-07-29
#    hostname: dokuwiki
#    environment:
#      - TZ=US/Chicago
#    volumes:
#      - /rdata/configs/dokuwiki:/config
#    ports:
#      - 8088:80
#    restart: always
#  pinry:
#    image: getpinry/pinry
#    hostname: pinry
#    volumes:
#      - /rdata/configs/pinry:/data
#    ports:
#      - 8089:80
#    restart: always
#  onlyoffice-server:
#    image: onlyoffice/documentserver
#    hostname: onlyoffice-server
#    ports:
#      - 8092:80
#    environment:
#      - NGINX_WORKER_PROCESSES=1
#      - NGINX_WORKER_CONNECTIONS=1024
#    restart: always
#  onlyoffice-client:
#    image: php:7.4-apache-buster
#    hostname: onlyoffice-client
#    ports:
#      - 8093:80
#    volumes:
#      - /rdata/configs/onlyoffice/w3:/var/www/html
#      - /rdata/onlydocs:/var/www/html/files
#    restart: always
