version: "3.3"

services:
  webserver:
    image: lipanski/docker-static-website:latest
    restart: always
    ports:
      - 80:3000
    volumes:
      - /rdata/www:/home/static
  filebrowser:
    image: filebrowser/filebrowser:v2
    hostname: filebrowser
    ports:
      - 8080:80
    volumes:
      - /rdata/docstore:/srv
      - /rdata/configs/filebrowser/filebrowser.db:/database.db
      - /rdata/music:/srv/Music (mapped)
      - /rdata/audiobooks:/srv/Audiobooks (mapped)
      - /rdata/onlydocs:/srv/onlydocs (mapped)
    environment:
      - VIRTUAL_HOST=filebrowser.local
    restart: always
