version: "3"

services:
  # Backend
  nginxserve:
    image: nginx
    hostname: nginx
    ports:
      - 80:80
      - 8008:8008 # debugging port
    volumes:
      - /rdata/configs/nginx/proxy_static_dynamic.conf.template:/etc/nginx/templates/default.conf.template
      #- /rdata/configs/nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      - /rdata/www:/var/www
    links:
      - phpfpm
    environment:
      - PROXY_USE_TLD=sun
    restart: always
  phpfpm:
    image: php:fpm
    hostname: phpfpm
    volumes:
      - /rdata/www:/var/www
    restart: always
  coredns:
    image: coredns/coredns
    command: "-conf /etc/coredns/Corefile"
    ports:
      - 5300:5300
      - "5300:5300/udp"
    volumes:
      - /rdata/configs/coredns:/etc/coredns
    restart: always
  # Applications
  audioserve:
    image: izderadicka/audioserve
    hostname: audioserve
    command: "--no-authentication /music /audiobooks"
    ports:
      - 3000:3000
    volumes:
      - /rdata/music:/music
      - /rdata/audiobooks:/audiobooks
    restart: always
  filebrowser:
    image: filebrowser/filebrowser
    hostname: filebrowser
    ports:
      - 8080:80
    volumes:
      - /rdata/docstore:/srv
      - /rdata/configs/filebrowser/filebrowser.db:/database.db
      #- /rdata/configs/filebrowser/.filebrowser.json:/.filebrowser.json
      - /rdata/music:/srv/Music (mapped)
      - /rdata/audiobooks:/srv/Audiobooks (mapped)
      - /rdata/onlydocs:/srv/onlydocs (mapped)
    restart: always
  homer:
    image: b4bz/homer
    hostname: homer
    ports:
      - 8086:8080
    volumes:
      - /rdata/configs/homer:/www/assets
    restart: always
  scrutiny:
    image: analogj/scrutiny
    hostname: scrutiny
    ports:
      - 8087:8080
    volumes:
      - /run/udev:/run/udev:ro
      - /rdata/configs/scrutiny:/scrutiny/config
    devices:
      - /dev/sda
#      - /dev/sdb
    cap_add:
      - SYS_RAWIO
    restart: always
  dokuwiki:
    image: ghcr.io/linuxserver/dokuwiki
    hostname: dokuwiki
    environment:
      - TZ=US/Chicago
    volumes:
      - /rdata/configs/dokuwiki:/config
    ports:
      - 8088:80
    restart: always
  pinry:
    image: getpinry/pinry
    hostname: pinry
    volumes:
      - /rdata/configs/pinry:/data
    ports:
      - 8089:80
    restart: always
#  homelights:
#    image: reneeverly/homelights:latest
#    hostname: homelights
#    network_mode: "bridge"
#    volumes:
#      - /rdata/configs/homelights/www/:/var/www
#    ports:
#      - 8091:80
#    restart: always
#  onlyoffice-server:
#    image: onlyoffice/documentserver
#    hostname: onlyoffice-server
#    ports:
#      - 8092:80
#    environment:
#      - NGINX_WORKER_PROCESSES=1
#      - NGINX_WORKER_CONNECTIONS=1024
#    restart: always
#  onlyoffice-client:
#    image: php:7.4-apache-buster
#    hostname: onlyoffice-client
#    ports:
#      - 8093:80
#    volumes:
#      - /rdata/configs/onlyoffice/w3:/var/www/html
#      - /rdata/onlydocs:/var/www/html/files
#    restart: always
