version: "1"

services:
  audioserve:
    image: izderadicka/audioserve
    command: "./audioserve --no-authentication /music /audiobooks"
    user: "${UID}:${GUID}"
    ports:
      - 3000:3000
    volumes:
      - /rdata/music:/music
      - /rdata/audiobooks:/audiobooks
    restart: always
  filebrowser:
    image: hurlenko/filebrowser
    user: "{$UID}:${GUID}"
    ports:
      - 8080:8080
    volumes:
      - /rdata/docstore:/data
      - /rdata/configs/filebrowser:/config
    restart: always
