version: "3"

services:
  audioserve:
    image: izderadicka/audioserve
    hostname: audioserve
    command: "--no-authentication /music /audiobooks"
    ports:
      - 3000:3000
    volumes:
      - /rdata/music:/music
      - /rdata/audiobooks:/audiobooks
    restart: always
  filebrowser:
    image: hurlenko/filebrowser
    hostname: filebrowser
    ports:
      - 8080:8080
    volumes:
      - /rdata/docstore:/data
      - /rdata/configs/filebrowser:/config
      - /rdata/music:/data/Music (mapped)
      - /rdata/audiobooks:/data/Audiobooks (mapped)
    restart: always
  homer:
    image: b4bz/homer
    hostname: homer
    ports:
      - 8086:8080
    volumes:
      - /rdata/configs/homer:/www/assets
    restart: always
  reverseproxy:
    image: nginx
    hostname: nginx
    ports:
      - 80:80
      - 8008:8008
    volumes:
      - /rdata/configs/nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      - /rdata/www:/var/www
    restart: always
  scrutiny:
    image: analogj/scrutiny
    hostname: scrutiny
    ports:
      - 8087:8080
    volumes:
      - /run/udev:/run/udev:ro
      - /rdata/configs/scrutiny:/scrutiny/config
    devices:
      - /dev/sda
#      - /dev/sdb
    cap_add:
      - SYS_RAWIO
    restart: always
  dokuwiki:
    image: ghcr.io/linuxserver/dokuwiki
    hostname: dokuwiki
    environment:
      - TZ=US/Chicago
    volumes:
      - /rdata/configs/dokuwiki:/config
    ports:
      - 8088:80
    restart: always
  pinry:
    image: getpinry/pinry
    hostname: pinry
    volumes:
      - /rdata/configs/pinry:/data
    ports:
      - 8089:80
    restart: always
