version: "3"

services:
  audioserve:
    image: izderadicka/audioserve
    command: "--no-authentication /music /audiobooks"
    ports:
      - 3000:3000
    volumes:
      - /rdata/music:/music
      - /rdata/audiobooks:/audiobooks
    restart: always
  filebrowser:
    image: hurlenko/filebrowser
    ports:
      - 8080:8080
    volumes:
      - /rdata/docstore:/data
      - /rdata/configs/filebrowser:/config
      - /rdata/music:/data/Music (mapped)
      - /rdata/audiobooks:/data/Audiobooks (mapped)
    restart: always
  homer:
    image: b4bz/homer
    ports:
      - 8086:8080
    volumes:
      - /rdata/configs/homer:/www/assets
    restart: always
  reverseproxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /rdata/configs/nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      - /rdata/www:/var/www
    restart: always
