version: "3"

services:
  audioserve:
    image: izderadicka/audioserve
    command: "--no-authentication /music /audiobooks"
    ports:
      - 3000:3000
    volumes:
      - /rdata/music:/music
      - /rdata/audiobooks:/audiobooks
    restart: always
  filebrowser:
    image: hurlenko/filebrowser
    ports:
      - 8080:8080
    volumes:
      - /rdata/docstore:/data
      - /rdata/configs/filebrowser:/config
      - /rdata/music:/data/Music (mapped)
      - /rdata/audiobooks/Audiobooks (mapped)
    restart: always
